import { build } from 'esbuild';

const buildConfig = {
  entryPoints: ['index.js'],
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs', // for pkg compatibility
  outfile: '.dist/index.cjs',
  external: ['node:*'],
  packages: 'bundle',
  minify: true,
  sourcemap: false,
  banner: {
    js: `// Generated by esbuild - all dependencies bundled
// Suppress SQLite experimental warnings before any imports
const originalProcessEmitWarning = process.emitWarning;
process.emitWarning = function(warning, type, code) {
  if (type === 'ExperimentalWarning' && warning.includes('SQLite')) {
    return;
  }
  return originalProcessEmitWarning.call(this, warning, type, code);
};`
  }
};

try {
  await build(buildConfig);
  console.log('✅ ESM → CommonJS bundling completed successfully');
} catch (error) {
  console.error('❌ Build failed:', error);
  process.exit(1);
}
